SELECT CONCAT ('Google','.com') AS ConcatFunction
SELECT ASCII (ProductID) NumberCodofID
FROM Products
SELECT ASCII ('0')
SELECT CHAR ('64') AS CodetoCharcater
SELECT LOWER ('SQL FUNCTIONS')
SELECT UPPER ('sql functions')
SELECT REPLACE ('TUTORIAL', 'T','t')
SELECT GETDATE()
SELECT DAY('2024/10/26') AS DAY
SELECT MONTH('2024/10/26') AS MONTH
SELECT YEAR('2024/10/26') AS YEAR